src/recipe_app/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from recipes import views
from .views import login_view, logout_view
"""
URL configuration for recipe_app project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('recipes/', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/recipes/urls.py
from django.urls import path
from . import views

#setting the 'home' path to be the default
app_name = 'recipes'
urlpatterns = [
    path('', views.recipe_details, name = 'recipe_details'),
    path('<int:pk>/', views.recipe_indiv, name='recipe_indiv'),
    path('search', views.search, name="search"),
    path('add/', views.add_recipe, name='add_recipe'),
    path('about', views.about, name="about")
]

src/recipes/models.py
from django.db import models

# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=120)
    cooking_time = models.IntegerField()
    ingredients = models.TextField(default="")
    separate_ingredients = models.TextField(default="", blank=True, null=True)
    difficulty = models.TextField(default="")
    description = models.TextField(default="")
    pic = models.ImageField(upload_to='recipes', default='no_picture.jpg')

    def __str__(self):
        return str(self.name)
    
    def calculate_difficulty(self):
        ing_num = len(self.separate_ingredients)
        if ing_num < 4 and self.cooking_time < 10:
            self.difficulty = "Easy"
        if ing_num < 4 and self.cooking_time >= 10:
            self.difficulty = "Medium"
        if ing_num >= 4 and self.cooking_time < 10:
            self.difficulty = "Intermediate"
        if ing_num >= 4 and self.cooking_time >= 10:
            self.difficulty = "Hard"

    def separate_ingredients_by_comma(self):
        self.separate_ingredients = self.ingredients.split(", ")

    def save(self, *args, **kwargs):
        self.calculate_difficulty()
        super().save(*args, **kwargs)

src/recipes/forms.py
from django import forms
from .models import Recipe
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

CHART__CHOICES = (          
   ('#1', 'Bar chart'),    # when user selects "Bar chart", it is stored as "#1"
   ('#2', 'Pie chart'),
   ('#3', 'Line chart')
)

#define class-based form (imported)
class RecipeSearchForm(forms.Form): 
   recipe_name = forms.CharField(max_length=120)
   chart_type = forms.ChoiceField(choices=CHART__CHOICES)

class RecipeForm(forms.ModelForm):
   class Meta:
      model = Recipe
      fields = ['name', 'ingredients', 'cooking_time', 'description', 'pic']
      widgets = {
         'description': forms.Textarea(attrs={'rows': 4}),
      }

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

src/recipes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Recipe
from .forms import RecipeSearchForm, RecipeForm, SignUpForm
import pandas as pd
from django.contrib.auth.decorators import login_required #authentication
from .utils import get_recipename_from_id, get_chart

# Create your views here.
def home(request):
    return render(request, "recipes/home.html")
@login_required
def recipe_details(request):
    recipes = Recipe.objects.all()
    return render(request, 'recipes/recipe_details.html', {'recipes': recipes})
@login_required
def recipe_indiv(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk)
    recipe.separate_ingredients_by_comma()    # split ingredients list
    recipe.calculate_difficulty()             # update difficulty
    recipe.save()                              
    return render(request, 'recipes/recipe_indiv.html', {'recipe': recipe})
@login_required
def search(request):
    form = RecipeSearchForm(request.POST or None)
    recipe_df = None
    recipe_name = None
    chart = None

    if request.method == 'POST':
        recipe_name = request.POST.get('recipe_name')
        chart_type = request.POST.get('chart_type')
        
        qs = Recipe.objects.filter(name=recipe_name)
        if qs:
            df = pd.DataFrame(qs.values('id', 'name', 'ingredients', 'cooking_time', 'difficulty', 'description', 'pic'))
            df['id'] = df['id'].apply(get_recipename_from_id)

            chart = get_chart(chart_type, df)
            recipe_df = df.to_html()

    context = {
        'form': form,
        'recipe_df': recipe_df,
        'chart': chart,
    }
    return render(request, 'recipes/search.html', context)

@login_required
def charts(request):
    recipes = Recipe.objects.all()

    # Difficulty Pie Chart
    difficulties = recipes.values_list('difficulty', flat=True)
    difficulty_counts = pd.Series(difficulties).value_counts()

    # Generate charts
    difficulty_chart = get_chart('pie', difficulty_counts)

    return render(request, 'recipes/charts.html', {
        'difficulty_chart': difficulty_chart
    })

@login_required
def add_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('recipes:recipe_details')  # Or wherever you want to send users after
    else:
        form = RecipeForm()

    return render(request, 'recipes/add_recipe.html', {'form': form})

@login_required
def about(request):
    return render(request, 'recipes/about.html')

def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')  # Redirect to login after signup
    else:
        form = SignUpForm()
    return render(request, 'users/signup.html', {'form': form})

src/recipes/templates/recipes/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recipe Details{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="side-column"></div>

    <div class="main-content">
        <h1>About Me</h1>

        <h1>Hello, World!</h1>
		<p>
			I am a programmer from Washington, D.C. As a former teacher, accessibility is my number one priority.
		</p>

        <section>
		   <h1>Work</h1>
		   <div class="grid">
		      <!-- Grid items TBA -->
		      <div class="grid__item">
			      <h2>Website Directory</h2>
			      <p>
			      	In this project, I compiled and linked a number of sites. It was written in Sublime Text Editor. the HTML and CSS pages are linked on Github.
			      </p>
			   </div>

			   <div class="grid__item">
			      <h2>qFilms API</h2>
			      <p>
			      	This manages movies, users, and lists of favorite movies. It is a RESTful back-end application that serves data to various projects. 
			      </p>
			      <a href="https://github.com/logicless-bt/QFilms-API">GitHub repository</a>
			   </div>

			   <div class="grid__item">
			      <h2>qFilms App (client)</h2>
			      <p>
			      	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.
			      </p>
			      <a href="https://github.com/logicless-bt/qfilms-client">GitHub repository</a>
			   </div>

			   <div class="grid__item">
			      <h2>Meet App</h2>
			      <p>
			      	The Meet App is a serverless, progressive web application that integrates with Google Calendar API. 
			      <a href="https://meet-five-eta.vercel.app/">See the project</a> <br>
                  <a href="https://github.com/logicless-bt/meet">GitHub repository</a>
			   </div>

			   <div class="grid__item">
			      <h2>Chat.io</h2>
			      <p>
			      	Built with React Native and Expo, this mobile chat application allows users to send messages, images, and locations with one another. It uses Google Firebase. 
			      </p>
			      <a href="https://github.com/logicless-bt/chat">GitHub repository</a>
			   </div>

			   <div class="grid__item">
			      <h2>QFilms Angular App (client)</h2>
			      <p>
			      	This is a reimagining of the qFilms app using Angular. It has the same functionalities but is created in a framework better suited to scaling. 
			      </p>
			      <a href="https://github.com/logicless-bt/qFilms-Angular-client-2">GitHub repository</a>
			   </div>


		   </div>
		</section>

    </div>

    <div class="side-column"></div>
</div>
{% endblock %}

src/recipes/templates/recipes/add_recipe.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Add Recipe{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/add_recipe.css' %}">
{% endblock %}

{% block content %}
<div class="main-content">
    <h2>Add a New Recipe</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

src/recipes/templates/recipes/home.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>
            Recipes Home
        </title>
        <link rel = 'stylesheet' href = "{% static 'css/home.css' %}">
    </head>
   
   <body>
        <div class="centered">
            <div>
                <h2>
                    RecipeGo
                </h2>
            </div>
            <div>
                <a href="{% url 'login' %}">
                    Log in
                </a>
            </div>
        </div>
   </body>
</html>

src/recipes/templates/recipes/recipe_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recipe Details{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/recipe_details.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="side-column"></div>

    <div class="main-content">
        <h1>All Recipes</h1>

        {% for recipe in recipes %}
            <div class="recipe">
                <a href="{% url 'recipes:recipe_indiv' recipe.pk %}">
                    {{ recipe.name }}
                </a> 
                <img src="{{ recipe.pic.url }}" alt="Recipe Image">
                <p><strong>Cooking time:</strong> {{ recipe.cooking_time }} minutes</p>
                <p class="description"><strong>Description:</strong> {{ recipe.description }}</p>
            </div>
        {% endfor %}
    </div>

    <div class="side-column"></div>
</div>
{% endblock %}

src/recipes/templates/recipes/recipe_indiv.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ recipe.name }}{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/recipe_indiv.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="side-column"></div>

    <div class="main-content">
        <h1>{{ recipe.name }}</h1>
        <img src="{{ recipe.pic.url }}" alt="{{ recipe.name }}">
        <p><strong>Cooking time:</strong> {{ recipe.cooking_time }} minutes</p>
        <p><strong>Difficulty:</strong> {{ recipe.difficulty }}</p>
        <p><strong>Ingredients:</strong> {{ recipe.ingredients }}</p>
        <p><strong>Description:</strong> {{ recipe.description }}</p>

        <a href="{% url 'recipes:recipe_details' %}" class="back-link">← Back to all recipes</a>
        <a href ="{%url 'logout' %}"> Logout </a>
    </div>

    <div class="side-column"></div>
</div>
{% endblock %}

src/recipes/templates/recipes/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Recipe Details{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/search.css' %}">
{% endblock %}

{% block content %}
<div class = "container">
    <div class = "side-column"></div>

    <div class = "main-content">
        <h2> Search for recipes! </h2>

        <hr>
        <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <button type="submit">search</button>

        <br>
        {% if recipe_df %}
            {{recipe_df|safe}} 
            
            <br>
            <img src="data:image/png;base64, {{chart|safe}}">
        {% else %}
            <h3> no data</h3>
        {% endif %}

        </form>
    </div>

    <div class = side-column></div>
</div>
{% endblock %}